apiVersion: apps/v1
kind: Deployment
metadata:
  name: your-app-staging
spec:
  replicas: 3
  selector:
    matchLabels:
      app: your-app
      environment: staging
  template:
    metadata:
      labels:
        app: your-app
        environment: staging
    spec:
      containers:
      - name: your-app-container
        image: your-container-image:staging
        ports:
        - containerPort: 8080
